[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.data.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.framework.js.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.loader.js"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"