[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.framework.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/Cosmic_Racer_Ver1.0.loader.js"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"